name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK 11 (required for Android projects)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'zulu'

    # Run Gradle tasks (e.g., clean, build, test)
    - name: Build with Gradle
      run: ./gradlew clean build

    # Run tests
    - name: Run tests
      run: ./gradlew test
